### PR TITLE
🔥 Turkish translations, many fixes!

### PR DESCRIPTION
**Pull request by eggsy**
Hello there!

Thank you for creating this - my new favourite - new tab extension, I hope you the best. I tried my best to help you on your journey and I fixed many issues, missing translations, and some missing code! I really liked your project and I wanted to contribute to it. I have tested this before I sent this PR so it's safe, but please run your own tests and let me know if I missed anything.

### This PR introduces

- 🔥 Turkish translations, for all pages and components!
- 🐛 Bug fixes (infinite loading in Top Sites etc.)
- 🐛 Missing titles: Bookmarks, Downloads, Sessions, System, Top Sites, Weather, Translate, and more...
- 🐛 Missing strings: Apps, Quick Links, RSS, Settings, Epitech, Isefac, and more...
- 🐛 Upgraded browser list package (which was throwing deprecation errors to console)

I really hope I didn't break anything, and I hope that I didn't mess with your coding habits like single quotes, indents and etc. that much. Keep this project updated! Good luck ♥

### CODE REVIEW

**Comment by eggsy** [comment]
@Alexays 🤔

**Comment by Alexays** [comment]
Hi @eggsy, sorry for the delay 😢 
I'll check this out before the end of the week!
Thanks for this PR! ❤️

**Comment by eggsy** [comment]
All right ☺️

**Review by Alexays — APPROVED** [review]

**Comment by Alexays** [comment]
Thanks for the changes!

**Pull request merged**
